name: Deploy to GitHub Pages

# Hangi durumlarda çalışacağını belirtin
on:
  push:
    branches:
      - main # Bu workflow, main dalına yapılan push işlemlerinde çalışır

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Kodları GitHub deposundan klonla
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. API anahtarını script.js'e inject et
      - name: Inject API Key into script.js
        run: |
          echo "window.API_KEY = '${{ secrets.API_KEY }}';" >> ./script.js

      # 3. GitHub Pages'e deploy et
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public # Yayınlanacak klasörü belirtin (örn. './public' veya './build' olabilir)
