name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # @v2'yi @v3 ile güncelledik

      - name: Inject API Key into script.js
        run: |
          echo "window.API_KEY = '${{ secrets.API_KEY }}';" >> ./public/script.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4 # @v3'ü @v4 ile güncelledik
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public # Yayınlanacak klasör
